version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/alexon1234/golang-api
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/api/main.go
  coverage:  
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/alexon1234/golang-api
    steps:
      - checkout
      - run: make coverage      
      - run: bash <(curl -s https://codecov.io/bash)      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - coverage
