version: 2.1
jobs:
  build-go_latest:
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/alexon1234/golang-api
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/api/main.go      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-go_latest
